#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/8ac0edb9-75f8-4c35-88e1-9bc5763afbc5

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int vpin5Velocidad;
  bool vPin1Adelante;
  bool vPin2Atras;
  bool vPin3Izquierda;
  bool vPin4Derecha;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define pin1MotorIzq D1
#define pin2MotorIzq D2
#define pin1MotorDer D3
#define pin2MotorDer D4

#define enableIzq D5
#define enableDer D6

int velocidad = 200;



void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  pinMode(pin1MotorIzq, OUTPUT);
  pinMode(pin2MotorIzq, OUTPUT);
  pinMode(pin1MotorDer, OUTPUT);
  pinMode(pin2MotorDer, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  iniciarCarro();

}

void iniciarCarro() {
  analogWrite(enableIzq, velocidad);
  analogWrite(enableDer, velocidad);

  if(vPin1Adelante){
    Serial.println("Mov Adelante");
    adelante();
  }

  if(vPin2Atras){
    Serial.println("Mov Atras");
    atras();
  }

  if(vPin3Izquierda){
    Serial.println("Mov Izquierda");
    izquierda();
  }

  if(vPin4Derecha){
    Serial.println("Mov Drecha");
    derecha();
  }

  if(!vPin1Adelante && !vPin2Atras && !vPin3Izquierda && !vPin4Derecha){
    Serial.println("Detenido");
    }
  Serial.println("Velocidad: " + String(velocidad));

  delay(1000);
}

void adelante() {
  //  analogWrite(enableIzq, velocidad);
  //  analogWrite(enableDer, velocidad);
  digitalWrite(pin1MotorIzq, 1);
  digitalWrite(pin2MotorIzq, 0);
  digitalWrite(pin1MotorDer, 1);
  digitalWrite(pin2MotorDer, 0);
}

void atras() {
  //  analogWrite(enableIzq, velocidad);
  //  analogWrite(enableDer, velocidad);
  digitalWrite(pin1MotorIzq, 0);
  digitalWrite(pin2MotorIzq, 1);
  digitalWrite(pin1MotorDer, 0);
  digitalWrite(pin2MotorDer, 1);
}

void izquierda() {
  //  analogWrite(enableIzq, velocidad);
  //  analogWrite(enableDer, velocidad);
  digitalWrite(pin1MotorIzq, 0);
  digitalWrite(pin2MotorIzq, 0);
  digitalWrite(pin1MotorDer, 1);
  digitalWrite(pin2MotorDer, 0);
}

void derecha() {
  //  analogWrite(enableIzq, velocidad);
  //  analogWrite(enableDer, velocidad);
  digitalWrite(pin1MotorIzq, 1);
  digitalWrite(pin2MotorIzq, 0);
  digitalWrite(pin1MotorDer, 0);
  digitalWrite(pin2MotorDer, 0);
}

void detener() {
  //  analogWrite(enableIzq, velocidad);
  //  analogWrite(enableDer, velocidad);
  digitalWrite(pin1MotorIzq, 0);
  digitalWrite(pin2MotorIzq, 0);
  digitalWrite(pin1MotorDer, 0);
  digitalWrite(pin2MotorDer, 0);
}


/*
  Since VPin1Adelante is READ_WRITE variable, onVPin1AdelanteChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVPin1AdelanteChange()  {
  // Add your code here to act upon VPin1Adelante change
  Serial.println("Adelante: " + String(vPin1Adelante));
}

/*
  Since VPin2Atras is READ_WRITE variable, onVPin2AtrasChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVPin2AtrasChange()  {
  // Add your code here to act upon VPin2Atras change
  Serial.println("Atras: " + String(vPin2Atras));

}

/*
  Since VPin3Izquierda is READ_WRITE variable, onVPin3IzquierdaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVPin3IzquierdaChange()  {
  // Add your code here to act upon VPin3Izquierda change
  Serial.println("Izquierda: " + String(vPin3Izquierda));

}

/*
  Since VPin4Derecha is READ_WRITE variable, onVPin4DerechaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVPin4DerechaChange()  {
  // Add your code here to act upon VPin4Derecha change
  Serial.println("Derecha: " + String(vPin4Derecha));

}






/*
  Since Vpin5Velocidad is READ_WRITE variable, onVpin5VelocidadChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVpin5VelocidadChange()  {
  // Add your code here to act upon Vpin5Velocidad change
  velocidad = (vpin5Velocidad * 250)/100;
  Serial.println("Velocidad: " + String(velocidad));

}
