// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fd5a1f36-aeab-4553-a560-2a977575fdef";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onVpin5VelocidadChange();
void onVPin1AdelanteChange();
void onVPin2AtrasChange();
void onVPin3IzquierdaChange();
void onVPin4DerechaChange();

int vpin5Velocidad;
bool vPin1Adelante;
bool vPin2Atras;
bool vPin3Izquierda;
bool vPin4Derecha;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(vpin5Velocidad, READWRITE, ON_CHANGE, onVpin5VelocidadChange);
  ArduinoCloud.addProperty(vPin1Adelante, READWRITE, ON_CHANGE, onVPin1AdelanteChange);
  ArduinoCloud.addProperty(vPin2Atras, READWRITE, ON_CHANGE, onVPin2AtrasChange);
  ArduinoCloud.addProperty(vPin3Izquierda, READWRITE, ON_CHANGE, onVPin3IzquierdaChange);
  ArduinoCloud.addProperty(vPin4Derecha, READWRITE, ON_CHANGE, onVPin4DerechaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
